#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module MrCos
    # ServiceErrorException signals that an error occured in server side
    # message member gives presicion (optional)
    class ServiceErrorException < ::Thrift::Exception
      include ::Thrift::Struct, ::Thrift::Struct_Union
      def initialize(message=nil)
        super()
        self.message = message
      end

      MESSAGE = 1

      FIELDS = {
        MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class OfferRecommendation
      include ::Thrift::Struct, ::Thrift::Struct_Union
      OFFERID = 1
      RELATEDOFFERS = 2
      SIMILAROFFERS = 3

      FIELDS = {
        OFFERID => {:type => ::Thrift::Types::STRING, :name => 'offerId'},
        RELATEDOFFERS => {:type => ::Thrift::Types::LIST, :name => 'relatedOffers', :element => {:type => ::Thrift::Types::STRING}},
        SIMILAROFFERS => {:type => ::Thrift::Types::LIST, :name => 'similarOffers', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
